language: python
sudo: required
dist: bionic
compiler: gcc

addons:
  apt:
    packages:
      - build-essential
      - libqt4-dev
      - tcl8.6-dev
      - tk8.6-dev
      - tcl
      - python3-pip
      - cmake
install:
  - sudo -H python3 -m pip install scikit-build
script:
  - sudo python3 setup.py install
