language: python
sudo: required
dist: bionic
compiler: gcc

addons:
  apt:
    packages:
      - build-essential
      - libqt4-dev
      - tcl8.6-dev
      - tk8.6-dev
      - tcl
script:
  - cmake .
  - make
  - sudo make install
